import * as Yup from 'yup';

export const AddStuffSchema = Yup.object({
  name: Yup.string().required(),
  quantity: Yup.number().positive().required(),
  condition: Yup.string().oneOf(['excellent', 'good', 'fair', 'poor']).required(),
  owner: Yup.string().required(),
});

export const EditStuffSchema = Yup.object({
  id: Yup.number().required(),
  name: Yup.string().required(),
  quantity: Yup.number().positive().required(),
  condition: Yup.string().oneOf(['excellent', 'good', 'fair', 'poor']).required(),
  owner: Yup.string().required(),
});

export const AddPinSchema = Yup.object({
  location: Yup.string().oneOf([
    'Outside',
    'CampusCenter',
    'ArtBuilding',
    'HolmesHall',
    'KraussHall',
    'POST',
    'MarineScienceBuilding',
    'UniversityHealthServices',
    'KennedyTheatre',
    'KellerHall',
    'WatanabeHall',
    'HawaiiInstituteGeophysics',
    'PhysicalScienceBuilding',
    'InformationTechnologyCenter',
    'BilgerHall',
    'BilgerAddition',
    'SakamakiHall',
    'KuykendallHall',
    'KuykendallAnnex',
    'Building37',
    'MillerHall',
    'WarriorRecreationCenter',
    'AdminServicesBuilding1',
    'AdminServicesBuilding2',
    'HemmenwayHall',
    'BachmanHall',
    'DeanHall',
    'GartleyHall',
    'FutureStudentSuccessCenter',
    'ArchitectureBuilding',
    'AndrewsOutdoorTheatre',
    'HawaiiHall',
    'LifeSciencesBuilding',
    'MooreHall',
    'ParadisePalms',
    'HamiltonLibrary',
    'HamiltonLibraryAddition',
    'EdmondsonHall',
    'SpaldingHall',
    'WebsterHall',
    'QueenLiliuokalaniCenterforStudentServices',
    'SaundersHall',
    'CrawfordHall',
    'BusinessAdministrationBuilding',
    'GeorgeHall',
  ]).required(),
  floor: Yup.number().positive().required(),
  description: Yup.string().required(),
});