import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import Footer from '@/components/Footer';
import PillNav from '@/components/PillNav';
import Providers from './providers';

const logo = '/img/logo.png';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js Application Template",
  description: "Generated by ics-software-engineering.github.io",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${geistSans.variable} ${geistMono.variable} wrapper`;
  return (
    <html lang="en">
      <body className={classString}>
       <Providers>
          <PillNav
            logo={logo}
            logoAlt="Cycle5ense Logo"
            items={[
              { label: 'Home', href: '/' },
              { label: 'Bottles4College Announcements', href: '/announcements' },
              { label: 'Manoa Bin Map', href: '/map' },
              { label: 'Sorting Guide', href: '/sorting-guide' },
              { label: 'Recycling Statistics', href: '/recycle-statistics' }
            ]}
            activeHref="/"
            className="custom-nav"
            ease="power2.easeOut"
            baseColor="#000000"
            pillColor="#ffffff"
            hoveredPillTextColor="#ffffff"
            pillTextColor="#000000"
            initialLoadAnimation
          />
          <main className="pt-4">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
