import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import Footer from '@/components/Footer';
import PillNav from '@/components/PillNav';
import Providers from './providers';
import 'leaflet/dist/leaflet.css';
import { auth } from '@/lib/auth';

const logo = '/img/logo.png';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Cycle5ense',
  description: 'Generated by ics-software-engineering.github.io',
  icons: {
    icon: '/icon.png',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const role = session?.user?.role;
  const isLoggedIn = !!session?.user;

  const defaultItems = [
    { label: 'Home', href: '/' },
    { label: 'Bottles4College Announcements', href: '/announcements' },
    { label: 'Manoa Bin Map', href: '/map' },
    { label: 'Sorting Guide', href: '/sorting-guide' },
    { label: 'Recycling Statistics', href: '/recycle-statistics' },
  ];

  const roleItems = role === 'ADMIN'
    ? [
      { label: 'Admin', href: '/admin' },
      { label: 'Add Announcement', href: '/add-announcement' },
    ]
    : role === 'USER'
      ? [{ label: 'My Profile', href: '/user' }]
      : [];

  const authItems = isLoggedIn
    ? [{ label: 'Sign Out', href: '/auth/signout' }]
    : [
      { label: 'Sign In', href: '/auth/signin' },
      { label: 'Sign Up', href: '/auth/signup' },
    ];

  const navItems = [...defaultItems, ...roleItems, ...authItems];

  const classString = `${geistSans.variable} ${geistMono.variable} wrapper`;

  return (
    <html lang="en">
      <body className={classString}>
        <Providers>
          <PillNav
            logo={logo}
            logoAlt="Cycle5ense Logo"
            items={navItems}
            activeHref="/"
            className="custom-nav"
            ease="power2.easeOut"
            baseColor="#2d4a2d"
            pillColor="#ffffff"
            hoveredPillTextColor="#ffffff"
            pillTextColor="#000000"
            initialLoadAnimation
          />
          <main className="pt-4">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
